### PR TITLE
Drupal matcher improvements

### LINKED ISSUE #11: Drupal 10 isn't detected
**Steps to reproduce**
1. Download and unzip latest Drupal (version 10): https://www.drupal.org/download-latest/zip
2. Run `bin/wappspector.php <path-to-drupal> --no-recursive`
3. Nothing is found

**Actual result**
Only PHP technology is found

**Expected result**
Drupal is found with version 10

### PR DESCRIPTION
**Pull request by untone-survive**
* Fix regex for Drupal versions > 9
* Allow matcher to detect Drupal even if no version info was found

### CODE REVIEW

**Review by xgin — APPROVED** [review]

File: src/WappMatchers/DrupalMatcher.php [hunk 1]
```diff
@@ -13,12 +13,12 @@ class DrupalMatcher implements WappMatcherInterface
...
         [
-            'file' => '/modules/system/system.info',
+            'file' => 'modules/system/system.info',
             'regex' => "/version\\s*=\\s*\"(\\d\\.[^']+)\"[\\s\\S]*project\\s*=\\s*\"drupal\"/",
         ],
         [
-            'file' => '/core/modules/system/system.info.yml',
-            'regex' => "/version:\\s*'(\\d\\.[^']+)'[\\s\\S]*project:\\s*'drupal'/",
+            'file' => 'core/modules/system/system.info.yml',
+            'regex' => "/version:\\s*'(\\d+\\.[^']+)'[\\s\\S]*project:\\s*'drupal'/",
```
Comment (untone-survive) [inline src/WappMatchers/DrupalMatcher.php:21]: couldn't detect versions with two digits ¯\_(ツ)_/¯
